config/routes.rb
Buildbounty::Application.routes.draw do

  resources :submissions

  resources :tags

  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/discover', to: 'static_pages#discover', via: 'get'
  match '/start', to: 'bounties#new', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/bounties/search', to: 'bounties#search', via: 'get'
  match '/bounties/:id/imageurl', to: 'bounties#imageurl', via: 'get'

  resources :bounties
  resources :follows
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resource :tags
  get '/bounties/:bid/submissions/:id' =>'submissions#show'
  

  

end

app/models/bounty.rb
class Bounty < ActiveRecord::Base
		belongs_to :user, class_name: "User"
		validates :user_id, presence: true
		has_many :follows, foreign_key: "bounty_id",
                                   class_name:  "Bounty",
                                   dependent:   :destroy
        has_many :taggings
        has_many :tags, through: :taggings
        has_many :submissions

        #attr_accessible :mimage
        # This method associates the attribute ":avatar" with a file attachment
		has_attached_file :mimage, styles: {
    		tiny: '30x30#',
    		card: '200x150#',
    		medium: '300x300#'
  		}, :default_url => "/images/:style/missing.png"

        def self.tagged_with(name)
        	Tag.find_by_name!(name).bounties
        end

        def self.tag_counts
        	Tag.select("tags.*, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
        end

        def tag_list
        	tags.map(&:name).join(", ")
        end

        def tag_list=(names)
        	self.tags = names.split(",").map do |n|
        		Tag.where(name: n.strip).first_or_create!
        	end
        end
end

app/controllers/bounties_controller.rb
class BountiesController < ApplicationController
  before_action :set_bounty, only: [:show, :edit, :update, :destroy]

  # GET /bounties
  # GET /bounties.json
  def index
    @bounties = Bounty.all
  end

  # GET /bounties/1
  # GET /bounties/1.json
  def show
  end

  # GET /bounties/new
  def new
    @bounty = Bounty.new
  end

  # GET /bounties/1/edit
  def edit
  end

  def imageurl
    @bounty.mimage.url
  end

  # GET /bounties/1/edit
  def search
    render :json => search_function(params[:q])
  end

  # POST /bounties
  # POST /bounties.json
  def create
    @bounty = Bounty.new(bounty_params)
    @bounty.user_id = current_user.id
    respond_to do |format|
      if @bounty.save
        format.html { redirect_to @bounty, notice: 'Bounty was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bounty }
      else
        format.html { render action: 'new' }
        format.json { render json: @bounty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bounties/1
  # PATCH/PUT /bounties/1.json
  def update
    respond_to do |format|
      if @bounty.update(bounty_params)
        format.html { redirect_to @bounty, notice: 'Bounty was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bounty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bounties/1
  # DELETE /bounties/1.json
  def destroy
    @bounty.destroy
    respond_to do |format|
      format.html { redirect_to bounties_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bounty
      @bounty = Bounty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bounty_params
      params.require(:bounty).permit(:name, :user_id, :content, :mimage)
    end

    def search_function(search)
      if search
        Bounty.find(:all, :conditions => ["name LIKE ?", "%#{search}%"]).map{|b| {:name => b.name, :id => b.id, :image => b.mimage.url(:tiny) }}
      else
        Bounty.all.map{|b| {:name => b.name, :id => b.id, :image => b.mimage.url(:tiny) }}
      end
    end
end

app/helpers/bounties_helper.rb
module BountiesHelper
end

app/views/bounties/_form.html.erb
<%= form_for(@bounty) do |f| %>
  <% if @bounty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bounty.errors.count, "error") %> prohibited this bounty from being saved:</h2>

      <ul>
      <% @bounty.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :mimage %><br />
    <%= f.file_field :mimage %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bounties/edit.html.erb
<h1>Editing bounty</h1>

<%= render 'form' %>

<%= link_to 'Show', @bounty %> |
<%= link_to 'Back', bounties_path %>

app/views/bounties/index.html.erb
<h1>Listing bounties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bounties.each do |bounty| %>
      <tr>
        <td><%= bounty.name %></td>
        <td><%= bounty.user_id %></td>
        <td><%= bounty.content %></td>
        <td><%= link_to 'Show', bounty %></td>
        <td><%= link_to 'Edit', edit_bounty_path(bounty) %></td>
        <td><%= link_to 'Destroy', bounty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bounty', new_bounty_path %>

app/views/bounties/new.html.erb
<% provide(:title, 'Start') %>

<h1>New bounty</h1>

<%= render 'form' %>

<%= link_to 'Back', bounties_path %>

app/views/bounties/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @bounty.mimage.url(:medium) %>

<p>
  <strong>Name:</strong>
  <%= @bounty.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @bounty.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @bounty.content %>
</p>
    <%= render 'shared/follow_form' if signed_in? %>
Tags : <%= raw @bounty.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>

<br/>

<%= link_to 'Edit', edit_bounty_path(@bounty) %> |
<%= link_to 'Back', bounties_path(@bounty) %>

<br/>

<%= link_to 'New submission', new_submission_path(user_id: current_user.id, bounty_id: @bounty.id), class: "btn btn-large" %>