config/routes.rb
Buildbounty::Application.routes.draw do

  resources :submissions

  resources :tags

  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/discover', to: 'static_pages#discover', via: 'get'
  match '/start', to: 'bounties#new', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/bounties/search', to: 'bounties#search', via: 'get'
  match '/bounties/:id/imageurl', to: 'bounties#imageurl', via: 'get'

  resources :bounties
  resources :follows
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resource :tags
  get '/bounties/:bid/submissions/:id' =>'submissions#show'
  

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://google.com/">Test App</a>
    by Matt Ferrell
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.google.com/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Build Bounty", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Discover", discover_path %></li>
          <li><%= link_to "Start", start_path %></li>
          <li><%= render partial: "shared/search" %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuildBounty | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
<!--      <%= debug(params) if Rails.env.development? %> -->
    </div>
</body>
</html>